### ISSUE TITLE
decode error

### ISSUE THREAD

**Issue by raojay7** [ictnlp/DDRS-NAT#1]
Thank you for your work!
When running the shell in **Inference ** Step 1: Decode the test set with argmax decoding, I faced the error as follows:
Traceback (most recent call last):
  File "generate.py", line 383, in <module>
    cli_main()
  File "generate.py", line 379, in cli_main
    main(args)
  File "generate.py", line 41, in main
    return _main(args, sys.stdout)
  File "generate.py", line 191, in _main
    hypos = task.inference_step(
  File "/data1/workspace/DDRS-NAT/fairseq/tasks/fairseq_task.py", line 433, in inference_step
    return generator.generate(
  File "/root/anaconda3/envs/nmt/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data1/workspace/DDRS-NAT/fairseq/iterative_refinement_generator.py", line 229, in generate
    log_probs, decoder_out,_ ,_ = model.forward_decoder(
ValueError: too many values to unpack (expected 2)
and 
I checked this line, found that 
`            log_probs, decoder_out = model.forward_decoder(
                    prev_decoder_out, encoder_out, **decoder_options
            )`
the log_probs is missing.
How can I get the right results?

**Comment by shaochenze** [comment]
Thank you for being interested in our work! We have fixed the reported issue. Please download the current repository for decoding or replace the old file fairseq/models/nat/nonautoregressive_transformer.py with the [current file](https://github.com/ictnlp/DDRS-NAT/blob/master/fairseq/models/nat/nonautoregressive_transformer.py).

**Comment by raojay7** [comment]
Wonderful!
